project:
  type: website
  output-dir: docs

website:
  title: "PPPELab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - Members.qmd
      - href: about.qmd
        text: PI
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: arial

editor: visual

